# Generated by Django 5.2.8 on 2025-11-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o titulo do filme', max_length=100)),
                ('comentario', models.TextField(help_text='Digite um comentario', max_length=1000)),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
