# Generated by Django 5.2.8 on 2025-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
